- pom.xml
The previous version now fails since it is no longer present in Maven repo.
Build works with this new one - see  [Jenkins job](https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/view/Weld/view/Weld%203%20CI/job/Weld-3.x-jacoco/164/)
> Fix the version of jacoco-maven-plugin.

- bundles/osgi/pom.xml
Verified the contents on the original OSGi jar and the new one with Meld. The only difference was the `META-INF/services/` directory which is desired.
As for plugin execution order - both plugins are bound to same phase, `package`. Therefore, whichever plugin is listed first in `pom.xml` gets executed first. And that works well for us.
> WELD-2378 Fix WeldModule declaration in OSGi bundle

- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/decorator/invalid/DecoratorWithPrivateConstructorTest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/decorator/invalid/ImplementingBean.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/decorator/invalid/SomeDecorator.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/decorator/invalid/SomeInterface.java
- impl/src/main/java/org/jboss/weld/injection/producer/BeanInjectionTarget.java
So, after quite some time digging in this, I found that we in fact even verify this [in code](https://github.com/weld/core/blob/3.0.0.Final/impl/src/main/java/org/jboss/weld/injection/producer/BeanInjectionTarget.java#L148) already, but the [check for relaxed mode](https://github.com/weld/core/blob/3.0.0.Final/impl/src/main/java/org/jboss/weld/injection/producer/BeanInjectionTarget.java#L142) incorrectly skips this verification. Incorrectly, because the mode has nothing to do with this - this is a Jav lang. limitation; we cannot instantiate decorated bean without calling constructor (e.g. with Unsafe) because of potential data-loss.
Feedback and comments are welcome.
> WELD-2273 Decorating bean with private constructor is not allowed.

- jboss-as/pom.xml
With this change you can run command such as the following one to generate a patch for WFLY 10.1.0.Final (assuming you have prepared the patched WFLY previously ofc):
`mvn clean install -Pwfly-patch-gen -Dwildfly.download.version=10.1.0.Final -DpatchConfigFile=/home/manovotn/GitRepo/build/wildfly/patch-config-wildfly-10-weld-2.4.xml -DwildflyPatched=/home/manovotn/GitRepo/wildfly/dist/target/wildfly-10.1.0.Final -Denforcer.skip=true`
There are two options, you can either let Maven download the original, pristine WildFly (which is what the above command does) or you can define a path to already existing one using `-DwildflyOriginal=...`
NOTE: The plugin is in `Alpha` version, therefore our Enforcer plugin will start complaining, hence the need to silence it.
Comments/suggestions are …
> WELD-2397 Allow to create WildFly patch through Maven profile.

- impl/src/main/java/org/jboss/weld/bootstrap/WeldStartup.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/application/event/ear/noWebArchive/ApplicationContextInitializedEventFiredWithNoWebArchiveTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/application/event/ear/noWebArchive/Library.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/application/event/ear/noWebArchive/SessionBean.java
This does not seem fixable on WFLY side (so that Swarm stays untouched) and in the same time we cannot do much unless we want to break Weld API. Therefore we should probably revert the change and leave it like that (and think this through for 3.x).
We can leave this PR hanging here for a while and see if we can come up with anything better.
> WELD-2401 Revert the behaviour - this cannot be fixed on WFLY side.

- impl/src/main/java/org/jboss/weld/bean/proxy/InterceptedSubclassFactory.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/DecoratedInteraceWithDefaultMethodTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/defaultmethod/InterfaceDefaultMethodInterceptedTest.java
This PR is based on https://github.com/weld/core/pull/1703 from @hypnoce:
- redundant test removed
- we must obtain the current stack first otherwise
`DecoratedInteraceWithDefaultMethodTest` fails
> WELD-2405 Do not optimize self invocation for default methods

- impl/src/main/java/org/jboss/weld/bean/proxy/InterceptedSubclassFactory.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/Base.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/Child.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/InterceptorBridgeMethodTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/Juicy.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/MissileInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/SpecialBase.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/SpecialChild.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/bridgemethods/hierarchy/SpecialParent.java
- also expand InterceptorBridgeMethodTest
> WELD-2414 Fix InterceptedSubclassFactory

- impl/src/main/java/org/jboss/weld/bean/builtin/InstanceImpl.java
I think there is no need to cache the priority comparator per `Instance`. We don't expect intensive use of this functionality.
>  WELD-2258 InstanceImpl - do not cache priority comparator

- jboss-as/pom.xml
The execution of CI jobs on this PR also verifies that the CI job executes against patched version of WFLY 11.
> WFLY update should now target WildFly 11.

- impl/pom.xml
- impl/src/main/java/org/jboss/weld/config/WeldConfiguration.java
- impl/src/main/java/org/jboss/weld/util/reflection/Formats.java
- modules/ejb/pom.xml
- modules/jsf/pom.xml
- modules/jta/pom.xml
- modules/web/pom.xml
- pom.xml
- probe/core/pom.xml
- probe/core/src/main/java/org/jboss/weld/probe/InvocationMonitor.java
Replace FindBugs with SpotBugs.
SpotBugs found few more details in code which I adapted as part of this PR, feel free to disagree.
I will keep the profile name and threshold properties (etc.) named "findbugs" as it is well-known and many CI jobs use it.
> WELD-2462 Migrate from FindBugs to SpotBugs.

- impl/src/main/java/org/jboss/weld/bean/proxy/ProtectionDomainCache.java
Prevent NullPointerException in ProtectionDomainCache if
ProtectionDomain.getPermissions() returns null.
> WELD-2464: Prevent NPE in ProtectionDomainCache (2.4)

- impl/src/main/java/org/jboss/weld/bean/proxy/ProtectionDomainCache.java
Prevent NullPointerException in ProtectionDomainCache if
ProtectionDomain.getPermissions() returns null.
> WELD-2464: Prevent NPE in ProtectionDomainCache

- impl/src/main/java/org/jboss/weld/util/Observers.java
I did grep our codebase for these and I think this is the sole problematic case.
There were other occurrences of course, but:
* those in tests can be ignored (SE or integration)
* those is SE impl too as they are not relevant for WFLY
* those in core but related to `Configurators` API can only be used with CDI 2.0, so we are safe there as well
> WELD-2474 Use Weld's internal literals.

- impl/src/main/java/org/jboss/weld/annotated/slim/AnnotatedTypeIdentifier.java
- impl/src/main/java/org/jboss/weld/util/AnnotatedTypes.java
- jboss-tck-runner/src/test/tck20/tck-tests.xml
- tests/src/test/java/org/jboss/weld/tests/unit/util/AnnotatedTypesTest.java
- use SHA-1 hash for generated ids for synthetic types
- shorten bdaId - bean deployment archive id very often starts with context id
- shorten suffix - AnnodatedType added by an extension often has suffix starting with class FQCN
- shorten modified - use 0 and 1
> WELD-2477: Optimize string representation of AnnotatedTypeIdentifier

- impl/src/main/java/org/jboss/weld/bootstrap/ConcurrentValidator.java
- impl/src/main/java/org/jboss/weld/bootstrap/Validator.java
- impl/src/main/java/org/jboss/weld/bootstrap/WeldStartup.java
- impl/src/main/java/org/jboss/weld/bootstrap/WeldUnusedMetadataExtension.java
- impl/src/main/java/org/jboss/weld/config/ConfigurationKey.java
- impl/src/main/java/org/jboss/weld/logging/BootstrapLogger.java
- impl/src/main/java/org/jboss/weld/manager/BeanManagerImpl.java
- impl/src/main/java/org/jboss/weld/resources/ClassTransformer.java
- impl/src/main/java/org/jboss/weld/serialization/ContextualStoreImpl.java
- impl/src/main/java/org/jboss/weld/util/Beans.java
- probe/tests/src/main/java/org/jboss/weld/probe/tests/integration/JSONTestUtil.java
- probe/tests/src/test/java/org/jboss/weld/probe/tests/integration/ProbeObserversTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/ExcludedUnused.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/TestExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/TestExternalConfiguration.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/Unused.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedBeanRemovalTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedBinding.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedExcludeAnnotation.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedResolvableToInstance.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedResolvableToInstanceBase.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedWithExcludeAnnotation.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedWithName.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedWithObserver.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedWithProducer.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/bootstrap/unusedbeans/UnusedWithUnusedProducer.java
This is a POC for ideas around [WELD-2457](https://issues.jboss.org/browse/WELD-2457).
I've tested the changes with a small application (slightly modified [JSF numberguess](https://github.com/weld/core/tree/master/examples/jsf/numberguess) example with DeltaSpike core dependency) deployed to WildFly 12. When measuring the cold start of the app server the memory consumption was reduced by ~ 10% (~ 300 KB) at the cost of increasing the bootstrap time by ~ 5% (~ 60ms).
> WELD-2457: Make it possible to drop unused beans metadata 

- impl/src/main/java/org/jboss/weld/bootstrap/events/configurator/AnnotatedTypeBuilderImpl.java
- impl/src/main/java/org/jboss/weld/bootstrap/events/configurator/InjectionPointConfiguratorImpl.java
- impl/src/main/java/org/jboss/weld/bootstrap/events/configurator/ObserverMethodConfiguratorImpl.java
Not sure this is 'sensible enough'. It can blow up (and call toString()) from many scenarios so amount of useful information may vary.
> WELD-2484 Configurators should override toString()

- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/conversation/timeout/concurrent/ConversationLockTimeoutTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/custombeans/BeanConfiguratorFailureTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/custombeans/BeanConfiguratorWithNoCallbackTest.java
This basically puts those three tests back into a state where they are unaffected by WELD-2498 (no anonymous class deployed to server) so that their failures don't hinder our CI test results.
Fix and test for the issue itself will be in a separate PR.
> WELD-2498 Fix test deployments which fail because of this issue.

- .gitignore
- environments/se/core/.gitignore
- environments/se/tests/.gitignore
These files seem to be commonly generated in projects that are edited in VS Code (which uses headless Eclipse under the covers).
> Ignores .factorypath files in all project modules

- environments/servlet/core/src/main/java/org/jboss/weld/environment/servlet/WeldProvider.java
- environments/servlet/core/src/main/resources/META-INF/services/javax.enterprise.inject.spi.CDIProvider
WeldProvider is only used and referenced by Servlet Core it doesn't make sense to keep it into commons anymore.
Note: SE already has its own provider implementation.
> [WELD-2435] Moved WeldProvider to Servlet Core module

- impl/src/main/java/org/jboss/weld/context/beanstore/http/AbstractSessionBeanStore.java
I had a report of an NPE being thrown when resetHttpSessionAttributeOnBeanAccess is enabled. I was able to recreate locally and it looks like a simple null check to prevent AbstractSessionBeanStore from trying to set the attribute before it is created is sufficient.
> WELD-1130: Prevent setting a null instance as an attribute

- jboss-tck-runner/src/test/tck12/tck-tests.xml
TCK issue - https://issues.jboss.org/browse/CDITCK-624
TCK PR - https://github.com/cdi-spec/cdi-tck/pull/178
> Based on CDITCK-624 we need to update our 1.2 TCK exclude list.

- tests-arquillian/src/test/java/org/jboss/weld/tests/resources/proxy/weld1782/AbstractMessageListener.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/resources/proxy/weld1782/ApplicationScopedObserver.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/resources/proxy/weld1782/Controller.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/resources/proxy/weld1782/RequestScopeEventMessageDeliveryTest.java
Not sure this is actually useful - I've seen some weird intermittent failures on Jenkins with previous solution using `Timer`. Maybe countdown latch will help a bit...
> Make RequestScopeEventMessageDeliveryTest use CountDownLatch.

- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/context/propagation/AbstractBeanWithState.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/context/propagation/AppScopedBean.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/context/propagation/ContextPropagationSEService.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/context/propagation/ContextPropagationSETest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/context/propagation/ReqScopedBean.java
- impl/src/main/java/org/jboss/weld/contexts/AbstractBoundContext.java
- impl/src/main/java/org/jboss/weld/contexts/AbstractContext.java
- impl/src/main/java/org/jboss/weld/contexts/PassivatingContextWrapper.java
- impl/src/main/java/org/jboss/weld/contexts/unbound/RequestContextImpl.java
- pom.xml
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/AbstractBeanWithState.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/AppScopedBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/ContextPropagationService.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/ContextPropagationTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/ConversationScopedBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/ReqScopedBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/propagation/SessionScopedBean.java
A basis PR for discussions around context propagation in Weld (WELD-2497)
Shows propagation for buillt-in contexts (req., session, conversation + application).
There are two very similar tests, in SE and in EE.
Both test the same thing however note that for instance `RequestContext` implementation in SE differs versus that in EE (unbound versus bound versus HTTP). Also only subset of scopes can be used in SE.
> WELD-2497 Context propagation for built-in scopes.

- environments/se/core/src/main/java/org/jboss/weld/environment/se/Weld.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/synthethic/jarHandling/SomeInterface.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/synthethic/jarHandling/SyntheticArchiveWithPackageFromJarTest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/synthethic/jarHandling/foo/ImplOne.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/synthethic/jarHandling/foobar/ImplTwo.java
Prevents a problem of picking multiple packages from a JAR that has two or more package starting with the same String (e.g. `org.mine.foo`, `org.mine.foobar`).
> WELD-2535 correct Weld.handleJar behaviour.

- impl/src/main/java/org/jboss/weld/util/reflection/Formats.java
- impl/src/main/java/org/jboss/weld/xml/BeansXmlStreamParser.java
- impl/src/main/java/org/jboss/weld/xml/BeansXmlValidator.java
- pom.xml
We have had SpotBugs disabled for JDK 10+ as the project wasn't running there.
This is now fixed so I re-enabled our CI jobs to run spotbugs with higher JDKs.
This PR bumps version of SpotBugs to latest and also adds supression for three false positives that only pop-up on JDK 11 for some reason. As justification I linked their GH issue which I think is the cause.
> Upgrade SpotBugs versions, Suppress false positives on JDK 11

- README.md
- jboss-as/pom.xml
Came across this while creating patch for WFLY 14.
`2.0.1.Final` is the latest now.
> Bump verison of maven plugin used for WFLY patch generation.

- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/Consumer.java
This is to be able to test Weld against latest released final version of WFLY.
> Revert "Uncommented test reproducing WFLY-11125"

- pom.xml
CI does not run on JDK12 yet so the results might not be relevant, but at least will run regression tests with JDK8 and 11.
> WELD-2572 Updated classfilewriter version for JDK12

- impl/src/main/java/org/jboss/weld/bean/proxy/PrivateMethodHandler.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/passivating/serialization/interception/FooImpl.java
Fix for WELD-2574 that I verified with the reproducer in linked issue.
I'll try to think of an automated test for this (requires to enforce serialization) before proceeding to merge.
> WELD-2574 Make PrivateMethodHandler serializable.

- environments/common/src/main/java/org/jboss/weld/environment/deployment/discovery/AbstractDiscoveryStrategy.java
- environments/common/src/main/java/org/jboss/weld/environment/deployment/discovery/DiscoveryStrategy.java
- environments/common/src/main/java/org/jboss/weld/environment/deployment/discovery/DiscoveryStrategyFactory.java
- environments/common/src/main/java/org/jboss/weld/environment/logging/CommonLogger.java
Signed-off-by: Laird Nelson <ljnelson@gmail.com>
This experimental PR allows `DiscoveryStrategy` instances to be loaded using a `ServiceLoader`.  All tests in `weld/core` continue to pass.  Any and all feedback welcome.  A [discussion in the Weld forums](https://developer.jboss.org/thread/279931) sparked this idea.
> [WELD-2578] Permits DiscoveryStrategy instances to be loaded via ServiceLoader.

- impl/src/main/java/org/jboss/weld/bean/ManagedBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionTarget/dispose/DisposingExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionTarget/dispose/InjectionTargetDisposeTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionTarget/dispose/Widget.java
Fixes https://issues.jboss.org/browse/WELD-2580.
Signed-off-by: Laird Nelson <ljnelson@gmail.com>
> [WELD-2580] Ensure InjectionTarget#dispose(Object) method is called in ManagedBean implementation

- examples/pom.xml
This fixes example ftests locally. Hopefully Jenkins won't complain (they aren't run as part of PR checks).
> Fix htmlunit version used in example ftests.

- impl/src/main/java/org/jboss/weld/injection/producer/InterceptionModelInitializer.java
- impl/src/main/java/org/jboss/weld/logging/BeanLogger.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/privateFinalMethods/BeanWithPrivateFinalMethod.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/privateFinalMethods/BeanWithPrivateFinalMethodTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/privateFinalMethods/MyInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/privateFinalMethods/Watches.java
Note that `InterceptionModelInitializer` throws this exception on two places.
Second one is inside `initMethodDeclaredEjbInterceptors()` method but that one searches for method-level annotations in which case having the method private final is an error.
> WELD-2595 Allow for private final methods on intercepted beans.

- docs/reference/src/main/asciidoc/environments.asciidoc
- environments/servlet/core/src/main/java/org/jboss/weld/environment/jetty/JettyContainer.java
- environments/servlet/core/src/main/java/org/jboss/weld/environment/jetty/WeldDecorator.java
- environments/servlet/core/src/main/java/org/jboss/weld/environment/servlet/logging/JettyLogger.java
For https://issues.jboss.org/browse/WELD-2597
Sorry about this, but the changes for jetty-9.4.20 have had a tough time in review because of the two mechanism and somewhat confused names.
Thus we are considering a bit of a renaming... but in a way that will not break Weld-3.1.2, which will still work with either `cdi2` or `decorate` modules.
However, going forward, we'd like to have `cdi-decorate` or `cdi-spi` modules.
This PR reflects the proposed rename in https://github.com/eclipse/jetty.project/pull/3946.    It also includes support for continuing to use the `decorate` directly, but you only really need that if you are worried about people applying 3.1.2 documentation to 3.1.3 and beyond.
Note that this is still a draft proposal until 3946 is reviewed and we've gotten your feedback as …
> WELD-2597 Rename the attributes for Jetty integration #2587

- impl/src/main/java/org/jboss/weld/config/WeldConfiguration.java
This PR closes the InputStream for the weld.properties file in a finally block after the file is read. This will help avoid integration problems when weld is integrated into servers that expect files to be closed quickly after use.
> Close weld.properties in finally block

- impl/src/main/java/org/jboss/weld/config/WeldConfiguration.java
This PR closes the InputStream for the weld.properties file in a finally block after the file is read. This will help avoid integration problems when weld is integrated into servers that expect files to be closed quickly after use.
> Close weld.properties stream in finally block

- impl/src/main/java/org/jboss/weld/util/collections/ImmutableArrayList.java
- impl/src/main/java/org/jboss/weld/util/collections/ImmutableTinyList.java
- impl/src/main/java/org/jboss/weld/util/collections/ImmutableTinySet.java
- pom.xml
Related to https://github.com/weld/parent/pull/10.
Updates the parent to fetch in the new checkstyle version. Adds `equals` impls to our own set/list implementations to satisfy checkstyle.
> Update Weld parent, satisfy checkstyle.

- impl/src/main/java/org/jboss/weld/contexts/beanstore/AttributeBeanStore.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/session/destroy/SessionContextDestroyTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/session/destroy/SessionScopedBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/contexts/session/destroy/TestServlet.java
- HttpSessionContext#destroy(Contextual<?>) should always destroy the
underlying contextual instance
> WELD-2615: Fix AttributeBeanStore.remove()

- impl/src/main/java/org/jboss/weld/bootstrap/events/configurator/ObserverMethodConfiguratorImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/custom/CustomAsyncObserverExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/custom/FooBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/custom/ObserverConfiguratorForAsyncTest.java
Issue only impacts reading from `AnnotatedMethod`, if you use `ObserverMethod`, then it works just fine.
> WELD-2609 Fix OM configurator when reading from an AnnotatedMethod.

- impl/src/main/java/org/jboss/weld/util/bytecode/ClassFileUtils.java
I am not really happy with this as it means we will be seeing `IllegalAccess` warning again on JDK 11. 
However, `Unsafe` is a mess in JDK 12+ and not really working, so we cannot rely on that for future solutions anyway. Linked issue has also reported a failure with it on 11 even though we don't know the exact setup (but it has something to do with modular setup which is likely).
We now have EE integrators re-routed to the new SPI for several releases, so this problem concerns mainly SE (and possibly servlet?). I don't think there is a solution we could take that would work in both, JDK 8 and JDK 11+ and for declaring classes in JDK 11+ there is likely still the issue of not being able to declare class with different `ProtectionDomain` via new API. I am not sure we need that in SE …
> WELD-2613 Remove Unsafe usage from class defining logic.

- impl/src/main/java/org/jboss/weld/bootstrap/enablement/Item.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/atd/minvaluepriority/AfterTypeDiscoveryObserver.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/atd/minvaluepriority/MinValuePriorityAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/atd/minvaluepriority/MinValuePriorityTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/atd/minvaluepriority/NormalAlternative.java
This PR fixes an integer overflow issue when sorting alternatives with a priority of `Integer.MIN_VALUE`, and includes a test proving the fix.
> WELD-2628 Fix integer overflow when sorting alternatives

- environments/servlet/core/src/main/java/org/jboss/weld/environment/servlet/deployment/WebAppBeanArchiveScanner.java
See latest discussion in https://issues.redhat.com/browse/WELD-2570.
Changed WebBeanArchiveScanner such that first it resolves, the real path of the file found through the servelet context, and afterwards compares that to the beans.xml file paths found in the classpath.
This avoids duplicate entries in settings where the deployment specifies a logical path for the server that is different from the actual file path.
> WELD-2570 Fix WebAppBeanArchiveScanner not excluding duplicate bean.xml correctly

- bundles/osgi/pom.xml
- environments/se/build/pom.xml
- environments/servlet/build/pom.xml
- environments/servlet/core/pom.xml
- probe/core/pom.xml
Javadoc creation was manually tested.
Note that bundle plugin for OSGi needs update to work with anything containing JMPS modules but that will come with API upgrade.
Also, there is an exclusion from undertow dep to prevent old `@Generated` annotation leaking in which then breaks generated classes from jboss logging processor.
> Backport javadoc creation changes and few other tweks from 3.1.

- docs/reference/pom.xml
For some reason I accidentally changed the HTML page name. It should stay `index.html`.
> Generated HTML docs should have index.html as page name.

- bundles/osgi/pom.xml
3.1 variant of https://github.com/weld/core/pull/2159 to make sure this fix lands on both branches.
Again, CI results apart from Travis are to be temporarily ignored.
> WELD-2645 Change OSGi export statement for modules.

- .github/workflows/ci-actions.yml
- .travis.yml
This is a draft and will not yet pass because it doesn't yet use EE 9 version of WFLY. I have talked to Brian and there is a good chance there will be nightly builds of those later this week.
So instead of creating a hacky build that needs several snapshots, I'd rather consume their nightly.
The testing setup is otherwise identical to that of 3.1 branch with the exception of different cache setup so that both branches use their own cache.
> Create GH Actions config file

- impl/src/main/java/org/jboss/weld/xml/BeansXmlStreamParser.java
- tests/src/test/java/org/jboss/weld/tests/unit/bootstrap/xml/cdi30/Beans30XmlParsingTest.java
- tests/src/test/resources/org/jboss/weld/tests/unit/bootstrap/xml/cdi30/cdi30-beans.xml
This updates BeansXmlStreamParser to recognise the new jakartaee URI for beans.xmls [as per the spec](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#_major_changes)  
This fixes https://issues.redhat.com/browse/WELD-2649
> WELD-2649 Add jakartaee URI to BeansXmlStreamParser

- impl/src/main/java/org/jboss/weld/bootstrap/AnnotatedTypeLoader.java
I think something as simple as this might be able to solve the problem.
There is no automated test attached because there is failure, just WARN logging happening. To test it, I used a reproducer on my branch - https://github.com/manovotn/core/tree/weld2652_reproducer
> WELD-2652 Do not try to load classes from META-INF/versions.

- environments/servlet/tests/jetty/pom.xml
This is currently breaking other PR tests for master because se-servlet coop tests are using it.
> Jetty servlet tests should have parent version 4.0.1.

- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
- impl/src/main/java/org/jboss/weld/util/Proxies.java
See https://issues.redhat.com/browse/WELD-2618 for more information on what is the current "issue" with the creation process and for reproducer.
I did use the same test the aforementioned issue has to confirm results although I chose not to add it into this PR as it uses not-so-nice reflections to invoke the method because whole `ProxyFactory` isn't public.
I do not have a string opinion about the current versus proposed proxy names, but I don't see a reason to make it more deterministic and readable.
@mkouba WDYT?
> WELD-2618 Make proxy name creation more deterministic.

- impl/src/main/java/org/jboss/weld/bean/proxy/InterceptedSubclassFactory.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/AbstractDecorator.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/DecoratingInterfaceWithDefaultMethodTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/FooBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/InterfaceWithDefaultMethod.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/NonAbstractDecorator.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/PlainInterface.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/DecoratingInterfaceWithDefaultMethodAndGenericsTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/DecoratorClass.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/Foo.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/GenericInterface.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/GenericInterfaceWithDefaultMethod.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/decorators/defaultmethod/notDecorated/generic/SomeBean.java
…s. Note that these tests were failing intermittently based on order in which interfaces were processed. Added a fix that subclasses don't create method delegation for abstract interface methods.
The removed code doesn't seem to have any purpose and was probably never invoked as it would have to result in `UnsupportedException` because the invocation was always made on an interface method that was abstract.
In this case it was problematic only if the superinterface (without default method impl) was processed first and generated the method code into subclass. Subsequently, the creation of proper delegation for default method was skipped because duplicate method was already present. Hence the failures were intermittent because based on ordering of interface processing, it might first …
> WELD-2647 Add two automated tests; one standard and one using generic… 

- bom/pom.xml
- pom.xml
New API version doesn't have any functional changes it just deprecates the `ProxyServices#supportsClassDefining`.
> Update Weld API to SP4.

- .gitignore
- environments/servlet/core/src/main/java/org/jboss/weld/environment/undertow/WeldServletExtension.java
Undertow uses the ImmediateInstanceFactory where a pre-instantiated instance of the Object should be used so this should not be wrapped in a WeldInstanceFactory as that attempts to create a second instance.
https://issues.redhat.com/browse/WELD-2664
This is the master PR for https://github.com/weld/core/pull/2296
> [WELD-2664] Don't wrap ImmediateInstanceFactory in WeldInstanceFactory.

- .gitignore
- environments/servlet/core/src/main/java/org/jboss/weld/environment/undertow/WeldServletExtension.java
Undertow uses the ImmediateInstanceFactory where a pre-instantiated instance of the Object should be used so this should not be wrapped in a WeldInstanceFactory as that attempts to create a second instance.
https://issues.redhat.com/browse/WELD-2664
> [3.1] [WELD-2664] Don't wrap ImmediateInstanceFactory in WeldInstanceFactory.

- impl/src/main/java/org/jboss/weld/bean/builtin/DecoratedBeanMetadataBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/ActualBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/DecoratorOne.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/DecoratorTwo.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/InterceptorOne.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/InterceptorTwo.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/MultipleDecoratorsMetadataTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/SomeBinding.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/builtinBeans/metadata/multiple/decorators/interceptors/SomeInterface.java
Automated test includes two decorators (which are the issue) and two interceptors (which seem to work fine), both of which use injected metadata, applied to a single bean method invocation.
The issue seems to be that decorators create a different creational context hierarchy than interceptors,
Interceptors always have a parent CC of the bean the intercept whereas with multiple decorators, that doesn't seem to be true.
With interceptors the CC hierarchy is: `ActualBean` -> [`DecoratorOne`, `DecoratorTwo`]
With decorators the CC hierarchy is: `ActualBean` -> `DecoratorOne` -> `DecoratorTwo`
The current "fix" here is really just a workaround. I need to figure out why are the CCs created differently for decorators in the first place.
> WELD-2673 @Decorated Bean<> injection point can get populated with wrong meta data

- jboss-tck-runner/pom.xml
- pom.xml
Fixes an issue where TCK tests that weren't properly named weren't executed in embedded container. See https://github.com/eclipse-ee4j/cdi-tck/issues/273#issuecomment-927090230
> Embedded TCK execution should use suite XML file.

- pom.xml
This version of Arq. container already supports CDI Lite extension execution through portable extension.
> Update Arq embedded container to version supporting Lite extensions.

- .github/workflows/ci-actions.yml
Since EE 10 cares about LTS Java versions, we should adapt the CI to do the same - we need to test with JDK 11 and 17.
> Update CI to run on JDK 11 and 17.

- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/metadata/EventPayload.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/metadata/FirstObserver.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/metadata/ObserverDeclaringBeanTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/observers/metadata/ObserverRegisteringExtension.java
The functionality defined by CDI spec already exists, so this PR only adds tests.
> WELD-2697 Add tests for ObserverMethod.getDeclaringBean

- .github/workflows/ci-actions.yml
- environments/se/core/pom.xml
- environments/se/pom.xml
- environments/se/tests/pom.xml
- environments/se/tests/src/test/resources/arquillian.xml
- environments/servlet/pom.xml
- impl/pom.xml
- inject-tck-runner/pom.xml
- jboss-tck-runner/pom.xml
- jboss-tck-runner/src/test/weld-se/arquillian.xml
- jboss-tck-runner/src/test/wildfly8/arquillian.xml
- pom.xml
- probe/tests/pom.xml
- probe/tests/src/test/resources/arquillian.xml
- tests-arquillian/pom.xml
- tests-arquillian/src/test/resources/wildfly-arquillian.xml
- tests/pom.xml
Should we add a jdk17 profile for activating the JDK17 settings included in this PR?
Signed-off-by: Scott Marlow <smarlow@redhat.com>
> WELD-2701 Changes for JDK 17 test execution. Additional arglines, removal of unused parameters, add JDK 17 to CI matrix.

- bundles/osgi/pom.xml
- pom.xml
To be fair, I am not really sure if this is everything needed to include `weld-lite-extension-translator` into OSGi bundle but I guess it should be. Feel free to oppose me if you know otherwise :-)
> WELD-2703 Include weld-lite-extension-translator in OSGi bundle.

- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
* Related to https://github.com/weld/core/pull/2264  
With JDK 11, Class.getPackage no longer returns null for classes in default packages.   
The following conditional branch also uses Class.getPackage() to determine the ProtectionDomain, so it is necessary to apply the above fix.  
https://github.com/weld/core/blob/f504fdf1cfc45a98d01c35e9ec294ec6ffa42ec9/impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java#L489-L490
> WELD-2704 Apply the change about Class.getPackage() to ProxyFactory.createProxyClass().

- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/AnnotationInfoImpl.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionInvoker.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionPhaseBase.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionPhaseEnhancement.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionPhaseRegistration.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/LiteExtensionTranslator.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ScannedClassesImpl.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/logging/LiteExtensionTranslatorLogger.java
Ensure that when we're wrapping an exception using the translation
logger, we retain the proper cause.
Also, if the cause is an InvocationTargetException, it won't have a
useful toString, so use the toString of its cause in the exception
message instead.
Fixes [WELD-2710](https://issues.redhat.com/browse/WELD-2710)
> Propagate causes in Lite Extension Translator

- lang-model-tck/pom.xml
- lang-model-tck/src/test/java/org/jboss/weld/lang/model/tck/LangModelExtension.java
- lang-model-tck/src/test/java/org/jboss/weld/lang/model/tck/LangModelTckTest.java
- lang-model-tck/src/test/resources/wildfly-arquillian.xml
Changes to how we execute lang model TCKs.
There are now profiles that allow for embedded and incontainer execution (with `-Dincontainer` just like in other modules).
I also slightly changed the deployment we use so that we can use `annotated` instead of `all` discovery mode.
I kept JMX protocol because otherwise I had issues executing the test against already running containers due to assertions not being enabled (no idea why?).
> WELD-2725 Add profile for lang model TCK execution on WFLY

- impl/src/main/java/org/jboss/weld/metadata/cache/QualifierModel.java
This PR avoids logging WARN about non-binding member types for qualifiers which are invalid anyway since they don't have `@Qualifier` and weren't registered via an extension.
There is no test attached since the only difference is a log output (or rather, the absence of it) but I used `ManagerAnnotationTest` to test this in various scenarios.
> WELD-2643 BM#isQualifier(), avoid logging WARN message when it is not needed

- impl/src/main/java/org/jboss/weld/resolution/AbstractAssignabilityRules.java
- impl/src/main/java/org/jboss/weld/resolution/CovariantTypes.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/assignability/recursiveGenerics/DuplicateRecursion.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/assignability/recursiveGenerics/MutualRecursion.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/assignability/recursiveGenerics/RecursiveGenericProducer.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/assignability/recursiveGenerics/RecursiveGenericsAssignabilityTest.java
A draft of how to handle recursive generic bean types.
The approach lies in special casing this scenario once we get to covariant type assignability checks.
We need to detect the recursion and then we assume assignability.
> WELD-2738 Bean type assignability for recursive generic types

- impl/src/main/java/org/jboss/weld/bootstrap/BeanDeployer.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/processBeanAttributes/specialization/VerifyingExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/lifecycle/processBeanAttributes/specialization/VetoTest.java
JIRA - https://issues.redhat.com/browse/WELD-2742
Relevant CDI spec part - https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_discovery_steps_full
PIT should be fired once and regardless of whether the bean is enabled or not whereas PP and PBA are conditional and only fired for enabled beans.
I've altered an existing test so that it captures how many times we fire `PIT<Bravo>`.
Before the change, this was twice (we re-fired PIT for each re-enabled bean), now it is correctly only once.
> WELD-2742 Avoid firing PIT multiple times if previously specialized bean was re-enabled

- impl/src/main/java/org/jboss/weld/bootstrap/events/AbstractDefinitionContainerEvent.java
- impl/src/main/java/org/jboss/weld/logging/BootstrapLogger.java
- pom.xml
JIRA - https://issues.redhat.com/browse/WELD-2741
Also bumps the TCK version.
The TCK test asserting this is currently excluded but was already changed to expect this behavior, see https://github.com/jakartaee/cdi-tck/issues/431 and [code](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/full/extensions/lifecycle/bbd/broken/passivatingScope/AddingPassivatingScopeTest.java)
> WELD-2741 Detecting a passivating non-normal scope should lead to deployment exception instead of definition

- .github/workflows/ci-actions.yml
- jboss-tck-runner/pom.xml
- jboss-tck-runner/src/test/tck/tck-tests-web.xml
- jboss-tck-runner/src/test/tck/tck-tests.xml
- pom.xml
Introduce POM property to be able to switch TCK suite XML file.
Introduce a separate XML file for TCKs with web profile and without it.
This is because an XML file with exclusion not present in given TCK profile results in an error (there are two such files already in the CDI TCK anyway).
Add relaxed mode testing into CI - this isn't a complete matrix. Inatead, it is a TCK run against WFLY and a full run of our TS w/o container.
> Add relaxed mode testing into CI runs

- docs/reference/src/main/asciidoc/beans.asciidoc
JIRA - https://issues.redhat.com/browse/WELD-2737
The notion of `@ManagedBean` should not be present as that's deprecated and not a bean defining annotation.
Also update wording to be the same as what CDI spec uses.
> WELD-2737 Correct wording for what classes are beans in accordance with CDI specification

- impl/src/main/java/org/jboss/weld/bean/proxy/DummyClassFactoryImpl.java
- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
- impl/src/main/java/org/jboss/weld/bean/proxy/util/WeldDefaultProxyServices.java
- pom.xml
CFW in version 1.3.0.Final includes following commit - https://github.com/jbossas/jboss-classfilewriter/commit/4028c251ecfdc9ded83e508b013aa306276057a3
This means as soon as `DefaultClassFactory.INSTANCE` gets initialized, you need `--add-opens` to be able to execute the code in there - else you're getting an exception.
Even though we never use CFW to define classes, this still affects us because of the way we instantiate `ClassFile` in our `ProxyFactory` - we use a deprecated method that now gets re-routed to a default implementation of the class factory.
In order to bypass this, we need to use a variant of the `ClassFile` method where we specify CL as well as `ClassFactory` instance. This PR uses dummy variant to do just that.
> WELD-2744 CFW update and needed changes to keep operating correctly on JDK 17+

- modules/ejb/src/main/java/org/jboss/weld/module/ejb/EnterpriseBeanProxyMethodHandler.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/enterprise/weld1234/Weld1234Test.java
https://issues.redhat.com/browse/WELD-1234
SessionObjectReference.isRemoved() can be expensive.  Let's avoid calling this per invocation, and instead return the fabricated toString() if the EJB was not found.
See https://github.com/wildfly/wildfly/pull/16885 for context.
> WELD-2747 Avoid calling SessionObjectReference.isRemoved() on every invocation.

- impl/src/main/java/org/jboss/weld/contexts/CreationalContextImpl.java
- impl/src/main/java/org/jboss/weld/manager/BeanManagerImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/interceptor/ManualInterceptorInstanceRetrievalTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/interceptor/MyBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/interceptor/MyBinding.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/interceptor/MyInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/synthBean/Child.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/synthBean/MyExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/synthBean/Parent.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/beanManager/getReference/synthBean/SimulateSynthBeanCreationalContextHierarchyTest.java
This PR:
* removes the `createChildCc` parameter from `BeanManagerImpl#getReference` and
* repairs the destruction and releasing logic in `CreationalContextImpl` while
* still allowing `DependentContextTest` to pass
Reference: https://issues.redhat.com/browse/WELD-2745
> WELD 2745 Restore proper getReference behavior from 5.1.0.Final and repair CreationalContextImpl destruction and releasing logic

- impl/src/main/java/org/jboss/weld/contexts/CreationalContextImpl.java
- impl/src/main/java/org/jboss/weld/manager/BeanManagerImpl.java
Attempts to solve a memory leak in dependent instance handling.
See the JIRA ([WELD-2750](https://issues.redhat.com/browse/WELD-2750)) for detailed description and a reproducer.
First commit:
* Makes sure the set of destroyed instance we keep in each CC is a `WeakReference` allowing GC to collect them. 
* Also changes how we create CC for non-dependent beans when obtaining injectable reference - we no longer unconditionally create child CC as that implies linked them together and potentially holding a reference to an already destroyed instance.
Second commit:
* An improvement on the second step of first commit - tries to avoid creating any superfluous CC when not needed. A side effect is that `BeanManagerImpl#getReference` can no longer return `null`. 
* However, after browsing code I …
> WELD-2750 Tweak how parent-child creational contexts are created. Use WeakReference to keep track of destroyed instance.

- modules/web/src/main/java/org/jboss/weld/module/web/servlet/WeldInitialListener.java
JIRA - https://issues.redhat.com/browse/WELD-2752
Lifecycle can be `null` if deployed app failed to start. In such case we want to skip context destruction to avoid throwing NPE.
> WELD-2752 WeldInitialListener will now only attempt context destruction if init was successful

- environments/se/core/src/test/java/org/jboss/weld/environment/se/test/provider/custom/CustomCDIProviderTest.java
- environments/servlet/tests/base/src/main/java/org/jboss/weld/environment/servlet/test/provider/CustomCDIProviderTest.java
This fix is not really an issue with current deps but recent changes to the `CDI` API class expose this problem (there is now an exception thrown on repeated set invocation).
> Fix tests with custom CDI providers

- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/event/options/timeout/IncompleteCustomExecutorServices.java
- impl/src/main/java/org/jboss/weld/bootstrap/events/ContainerLifecycleEventPreloader.java
- impl/src/main/java/org/jboss/weld/executor/AbstractExecutorServices.java
- impl/src/main/java/org/jboss/weld/executor/DaemonThreadFactory.java
- impl/src/main/java/org/jboss/weld/executor/FixedThreadPoolExecutorServices.java
- impl/src/main/java/org/jboss/weld/executor/TimingOutFixedThreadPoolExecutorServices.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/event/async/stage/CustomExecutorServices.java
Alternative approach to https://github.com/weld/core/pull/2880 and a solution for WELD-2755 JIRA.
This should go hand in hand with WFLY changes, i.e. https://github.com/wildfly/wildfly/pull/17193
We don't seem to leverage the `ThreadGroup` in any way so having explicit groups serves no purpose.
From the API, it is possible to just not define a group and roll with the default; note that we should do the same on WFLY side (`WeldExecutorServices`) unless there is some other restriction in play that I am not aware of yet.
> WELD-2755 Remove usage of ThreadGroup from Weld executors

- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/packPrivate/ProxyForInterceptedPackagePrivateBeanTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/packPrivate/api/Alpha.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/packPrivate/impl/AlphaImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/packPrivate/interceptor/MyInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/packPrivate/interceptor/SomeBinding.java
https://issues.redhat.com/browse/WELD-2758
> WELD-2758 Proxies for non-public class-based beans should reside in bean's package if possible

- modules/web/src/main/java/org/jboss/weld/module/web/context/beanstore/http/LazySessionBeanStore.java
I am not sure if this can lead to unexpected scenarios due to the fact that the bean store is lazy but at first sight it seems OK to propagate the exception as it is out of our control anyway.
> WELD-2762 Do not swallow exceptions occuring during HTTP session creation

- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/MyExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ProxyCreationForCdiBeanWithUnimplementedInterfaceTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ProxyCreationForEjbLocalTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ifaces/BeanIface.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ifaces/LocalInterface1.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ifaces/LocalInterface2.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ifaces/NotImplementedButDeclaredInterface.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/ifaces/NotImplementedIface.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/impl/CDIBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/classDefining/unimplemented/interfaces/impl/StatelessLocalBean.java
JIRA with more details - https://issues.redhat.com/browse/WELD-2763
Original issue that started this investigation - https://github.com/jakartaee/platform-tck/issues/1194
> WELD-2763 Correct how Weld chooses proxy package when a bean has unassignable interface type

- impl/src/main/java/org/jboss/weld/invokable/AbstractInvokerBuilder.java
- impl/src/main/java/org/jboss/weld/invokable/MethodHandleUtils.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/BeanInfoImpl.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionInvoker.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionPhaseRegistration.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/LiteExtensionTranslator.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ReflectionMembers.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/SyntheticComponentBuilderBase.java
Includes one tiny improvement to the Language Model implementation that should be clarified in the next version of the specification.
> improvements to the method invokers implementation

- impl/src/main/java/org/jboss/weld/bean/AbstractProducerBean.java
- impl/src/main/java/org/jboss/weld/bean/ProducerField.java
- impl/src/main/java/org/jboss/weld/bean/ProducerMethod.java
- impl/src/main/java/org/jboss/weld/bean/WeldBean.java
- impl/src/main/java/org/jboss/weld/resolution/AbstractTypeSafeBeanResolver.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/Alpha.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/AltBeanProducingAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/AltBeanProducingPrioritizedNonAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/Beta.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/Delta.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/Gamma.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/NonAltBeanProducingAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/NonAltBeanWithPrioProducingAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/ProducedByField.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/ProducedByMethod.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/ProducerExplicitPriorityTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/RegularBeanProducer.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/Bar.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/Foo.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/GloballyEnabledAlt.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/LocallyEnabledAlternative.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/ProducerOnLocallyEnabledAltTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/alternative/priority/complex/RegularProducer.java
Weld implementation for https://github.com/jakartaee/cdi/issues/556
Tests for this are on a TCK PR - https://github.com/jakartaee/cdi-tck/pull/499 (and this PR passes them)
I don't mind adding tests here as well, but it would basically be a duplication of the same ones - WDYT @mkouba?
> WELD-2768 support explicitly declaring @Priority on producers

- impl/src/main/java/org/jboss/weld/annotated/enhanced/jlr/EnhancedAnnotatedTypeImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerBeanSubclass.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerExtensionTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/MyExtension.java
Related to https://github.com/weld/core/pull/2903
This is a minimal change which corrects how we identify declaring class for a non-discovered annotated type (one that was tempered with by an extension for instance).
> WELD-2773 Incorrect producer field inheritance

- impl/src/main/java/org/jboss/weld/annotated/enhanced/jlr/EnhancedAnnotatedTypeImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerBeanSubclass.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/FieldProducerExtensionTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/producer/field/MyExtension.java
5.1 counterpart of https://github.com/weld/core/pull/2904
> WELD-2773 Prevent producer field inheritance when extension manipulates the annotated type.

- impl/src/main/java/org/jboss/weld/event/EventMetadataImpl.java
- impl/src/main/java/org/jboss/weld/event/ObserverNotifier.java
- impl/src/main/java/org/jboss/weld/manager/BeanManagerImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/event/EventQualifierTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/event/ObservingBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/event/Payload.java
Attempts to fix the missing `@Default` qualifier when firing events via `BeanManager.getEvent()` API.
> WELD-2775 Make sure BM#getEvent() adds @Default qualifier correctly

- bom/pom.xml
- docs/reference/pom.xml
- docs/reference/src/main/asciidoc/extend.asciidoc
- docs/reference/src/main/asciidoc/part5.asciidoc
- docs/reference/src/main/asciidoc/weldinvoker.asciidoc
- environments/se/core/src/main/java/org/jboss/weld/environment/se/ContainerLifecycleObserver.java
- impl/src/main/java/org/jboss/weld/bootstrap/events/AbstractProcessClassBean.java
- impl/src/main/java/org/jboss/weld/bootstrap/events/ProcessManagedBeanImpl.java
- impl/src/main/java/org/jboss/weld/invokable/AbstractInvokerBuilder.java
- impl/src/main/java/org/jboss/weld/invokable/MethodHandleUtils.java
- impl/src/main/java/org/jboss/weld/logging/Category.java
- impl/src/main/java/org/jboss/weld/logging/InvokerLogger.java
- impl/src/main/java/org/jboss/weld/util/Observers.java
- pom.xml
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/BuildCompatExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/ObservingExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/transformers/input/ObservingExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/transformers/output/ObservingExtension.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionInvoker.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionMethodParameterType.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/ExtensionPhaseRegistration.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/InvokerFactoryImpl.java
PR is still WIP and will require new Weld API version (see https://github.com/weld/api/pull/191)
Contains:
* Logging changes so that we use proper `Logger` interface
* Implement changes allowing to use Weld APIs without the need to type cast
* Remove leftover playground classes
* After some more thinking I decided we should keep them in; might save a headache or two in the future
* Documentation changes - we should mention the new API in our docs
* Revisit deployment validation of lookups and see if we could perform it differently
* This is IMO done correctly
* invokers do not use classical `InjectionPoint` (which is correct due to their nature) and validating them separately through `WeldInstance` works just fine
* Notably, this should respect the BM-per-archive structure that Weld uses …
> WELD-2780 collection of changes for the invokers API

- environments/common/src/main/java/org/jboss/weld/environment/deployment/discovery/jandex/SecurityActions.java
- environments/common/src/main/java/org/jboss/weld/environment/util/SecurityActions.java
- environments/se/core/src/main/java/org/jboss/weld/environment/se/SecurityActions.java
- environments/se/core/src/main/java/org/jboss/weld/environment/se/Weld.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/none/NoExtensionFoundTest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/registered/DiscoveredBce.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/registered/ExtensionRegisteredManuallyTest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/registered/ManuallyRegisteredBce.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/registered/RegisteredAndDiscoveredExtensionsTest.java
- environments/se/tests/src/test/java/org/jboss/weld/environment/se/test/extension/build/compatible/registered/SomeBean.java
- environments/servlet/core/src/main/java/org/jboss/weld/environment/servlet/SecurityActions.java
- impl/src/main/java/org/jboss/weld/bean/proxy/DecorationHelper.java
- impl/src/main/java/org/jboss/weld/bean/proxy/DefaultProxyInstantiator.java
- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyFactory.java
- impl/src/main/java/org/jboss/weld/bean/proxy/ProxyInstantiator.java
- impl/src/main/java/org/jboss/weld/injection/Exceptions.java
- impl/src/main/java/org/jboss/weld/security/NewInstanceAction.java
- impl/src/test/java/org/jboss/weld/tests/unit/security/ReflectionTest.java
- modules/ejb/src/main/java/org/jboss/weld/module/ejb/SessionBeanProxyInstantiator.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/extension/AbstractInterceptor.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/lhotse/fst/GenericDAO.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/interceptors/tb/GenericDAO.java
- weld-lite-extension-translator/src/main/java/org/jboss/weld/lite/extension/translator/LiteExtensionTranslator.java
Add the ability to manually register BCE in Weld SE without the need to perform discovery.
I believe this should eventually bubble up to `SeContainerInitializer` and be part of the CDI SE API (cc @Ladicek; this is something I mentioned a [long] while ago)
We already have similar methods in place for portable extensions.
> Weld-2772 Allow to register BCE in Weld SE without discovery

- bundles/osgi/pom.xml
This should be the cause of the recent release failure - the order of these plugin wasn't explicit and some Maven change prompted ordering change leading to signing files before the shade plugin did it's changes on them.
> Fix plugin execution order in osgi module

- .github/workflows/release.yml
This fixes the doc from Beta4 release to look like it's for SNAPSHOT.
Other parts should be correct.
> Release script - checkout tag before building docs

- impl/src/main/java/org/jboss/weld/xml/BeansXmlValidator.java
Follow up on https://github.com/weld/core/pull/3035
> Fix BeansXmlValidator#loadXsds to operate on StreamSource types

- .github/project.yml
- .github/workflows/release.yml
- .gitignore
- dist/BUILD.md
- dist/README.md
- dist/build.gradle
- environments/se/build/pom.xml
- environments/servlet/build/pom.xml
- pom.xml
- tests-arquillian/src/test/java/org/jboss/weld/tests/accessibility/bce/BceInLibTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/accessibility/bce/lib/MyBeanCreator.java
Change 5.1 branch to work similarly to main branch.
Apply several small changes changes needed for that.
Also bump Weld parent to version 52.
> Release setup update

- .github/workflows/ci-actions.yml
- tests-arquillian/src/test/java/org/jboss/weld/tests/accessibility/bce/lib/MyBce.java
Formatting fix.
Correction to CI setup WRT formatter enforcement.
Upgrade WFLY version.
> Minor fixes for 5.1

- impl/src/main/java/org/jboss/weld/annotated/enhanced/jlr/EnhancedAnnotatedTypeImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/Foo.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/FooSpecialized.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/FooSpecializedNoBeanDef.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/MyExtension.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/SpecializationDiscoveryTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/injectionPoint/resource/extension/SpecializationExtensionTest.java
- tests-arquillian/src/test/resources/org/jboss/weld/tests/injectionPoint/resource/extension/web.xml
JIRA - https://issues.redhat.com/browse/WELD-2798
> WELD-2798 Correct injection into injected @Resource fields; add automated test

- impl/src/main/java/org/jboss/weld/util/ServiceLoader.java
This should resolve https://issues.redhat.com/browse/WELD-2800
`java.net.URL.openStream` uses a jar cache. Thus the jar file is kept in memory as long as the Glassfish server is alive, and thus the jar file in "glassfish\domains\domain1\applications" cannot be deleted on windows when the app is undeployed.
Workaround: set `URLConnection.setUseCaches(false)` before accessing the InputStream:
```java
URLConnection jarConnection = serviceFile.openConnection();
jarConnection.setUseCaches(false);
is = jarConnection.getInputStream();
```
I pushed it to the 5.1 branch as GlassFish 7.0.18 uses Weld 5.1.3.Final, and I hope that this fix makes it to next Glassfish.
I don't have much git experience and never pushed to a branch, so please be patient with me if I did this wrong ;-)
> [WELD-2800] Don't use jar cache in ServiceLoader.loadServiceFile

- impl/src/main/java/org/jboss/weld/util/ServiceLoader.java
Weld 6 counterpart for https://github.com/weld/core/pull/3069
>  [WELD-2800] Don't use jar cache in ServiceLoader.loadServiceFile

- .github/workflows/ci-actions.yml
- jboss-tck-runner/pom.xml
- jboss-tck-runner/src/test/tck/tck-tests-web.xml
- pom.xml
JIRA - https://issues.redhat.com/browse/WELD-2778
> WELD-2778 Re-introduce EE parts of CDI TCKs into regular coverage

- impl/src/main/java/org/jboss/weld/bean/builtin/BeanManagerBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/el/injection/ELAwareBeanManagerInjectionTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/el/injection/ELAwareInjectionBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/el/injection/ELAwareTestBean.java
Allow `ELAwareBeanManager` to be injected, as [required in the Web Profile spec](https://jakarta.ee/specifications/webprofile/11/jakarta-webprofile-spec-11.0-m4#obtaining-elawarebeanmanager)
For [WELD-2808](https://issues.redhat.com/browse/WELD-2808)
> WELD-2808 Allow injection of `ELAwareBeanManager`

- impl/src/main/java/org/jboss/weld/event/ObserverMethodImpl.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/ExtensionTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/extensions/SimpleExtension.java
JIRA - https://issues.redhat.com/browse/WELD-2811
> WELD-2811 Allow to inject other BM subtypes into container lifecycle observer methods

- impl/src/main/java/org/jboss/weld/invokable/AbstractInvokerBuilder.java
- impl/src/main/java/org/jboss/weld/invokable/InvokerValidationUtils.java
- impl/src/main/java/org/jboss/weld/invokable/MethodHandleUtils.java
- impl/src/main/java/org/jboss/weld/logging/InvokerLogger.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/exceptions/ExceptionTestBean.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/exceptions/InvokableExceptionsTest.java
- tests-arquillian/src/test/java/org/jboss/weld/tests/invokable/exceptions/ObservingExtension.java
Some of the exception messages you can get from calling an Invoker with the wrong arguments are a bit obtuse and I wanted to look at providing a bit more information.
To do this, I'm doing extra checks before calling the method to ensure that:
- Enough arguments have been passed in
- Non-looked-up arguments have the correct type
- Non-looked-up primitive arguments are not null
- Non-looked-up instances have the correct type
- The instance is not null if the method is non-static
Most of these checks have to be done before the argument array is spread to the actual arguments, since the MethodHandles implementation will throw an exception there if things are the wrong types.
If there are transformers, type checking is done against the input type of the transformer.
The null check for the …
> WELD-2812 Improve Invoker exception messages

- pom.xml
Similar to what we changed in main branch and for 6.x
> Update Parent to 56, explicitly declare compiler and javadoc target/source
